export const COPY = {
  FR: {
    nav: ["L'Expérience", "Galerie", "Réservation"],
    eyebrow: "— Sur réservation uniquement",
    headlineA: "L'obscurité",
    headlineB: "n'a jamais été aussi",
    headlineC: "éclatante.",
    sub: "Vivez l'expérience Osmose : un refuge secret au cœur de la ville, conçu pour l'intimité et l'éveil des sens.",
    cta: "Réserver votre parenthèse",
    suiteRef: "Suite N°VII · Paris",
    vertical: "Black Room — Édition Privée — MMXXVI",
    scroll: "Faire défiler",
    manifeste: {
      kicker: "Manifeste",
      h1a: "Une parenthèse",
      h1b: "hors du temps,",
      h1c: "à l'abri du monde.",
      body1: "Osmose n'est pas un hôtel. C'est un écrin privé, une chambre noire pensée comme un théâtre intime où chaque ombre, chaque reflet d'or a sa raison d'être.",
      body2: "Tout y a été mesuré — la température de la lumière, la densité du silence, la profondeur du velours — pour qu'il ne reste plus que vous, et l'instant.",
      signature: "Architecte d'intérieur, Paris",
    },
    suite: {
      kicker: "La Suite",
      title1: "Cinquante mètres carrés",
      title2: "de pénombre ciselée.",
      body: "Bois cannelé, draps de coton lavé bleu nuit, lumière d'or rasante. Une chambre conçue comme une seule respiration : large, basse, enveloppante.",
      specs: [
        { k: "Surface", v: "50 m²" },
        { k: "Lit", v: "King Size" },
        { k: "Capacité", v: "2 hôtes" },
        { k: "Insonorisation", v: "Studio" },
      ],
    },
    experience: {
      kicker: "L'Expérience",
      title1: "Trois rituels",
      title2: "pour s'oublier.",
      intro: "Chaque séjour est composé comme une partition : trois mouvements, une même intention — ralentir, ressentir, disparaître.",
      cta: "Découvrir",
      tiles: [
        { num: "i.", title: "Le Bain de Nuit", body: "Spa privé sous lumière saphir. Eaux frissonnantes, vapeur, et l'éclat minéral d'un instant suspendu." },
        { num: "ii.", title: "Le Salon", body: "Velours, marbre brut, fauteuils enveloppants. Un théâtre d'ombres pour une conversation à deux voix." },
        { num: "iii.", title: "Le Bar Secret", body: "Cave à spiritueux, vinyles choisis, douceurs sucrées. Servi en chambre, sans un mot." },
      ],
    },
    galerie: {
      kicker: "Galerie",
      title1: "Indices",
      title2: "d'un huis-clos.",
      note: "Cliquez pour entrer",
      cta: "Voir la galerie complète",
      quote: "Un lieu où l'on n'allume jamais toutes les lumières — c'est là que tout commence.",
      quoteAuthor: "Vogue Living",
    },
    reservation: {
      kicker: "Réservation",
      title1: "Discrétion absolue,",
      title2: "hospitalité ciselée.",
      body: "Notre conciergerie vous répond sous trois heures. Accès par code privé, arrivée autonome, services additionnels sur simple message.",
      f: {
        name: "Nom", email: "Email", phone: "Téléphone",
        arrival: "Arrivée", nights: "Durée", guests: "Hôtes",
        nightsS: "nuit", nightsP: "nuits", guestsS: "hôte", guestsP: "hôtes",
        message: "Souhaits particuliers (optionnel)",
        submit: "Envoyer la demande", submitted: "Demande envoyée",
        disclaimer: "Réponse confidentielle sous 3h",
      },
      aside: {
        kicker: "À partir de",
        unit: "nuit",
        contact: "Conciergerie privée",
        includes: [
          "Accès spa privé et lounge",
          "Mini-bar de signature",
          "Linge en coton lavé, peignoirs",
          "Check-in autonome 24/7",
        ],
      },
    },
    footer: {
      tagline: "Une édition privée au cœur du Marais. Sur réservation uniquement.",
      col1: "Maison", col2: "Adresse", col3: "Suivez-nous",
      links1: ["L'Expérience", "La Suite", "Galerie", "Réservation", "Mentions légales"],
      fine: "Site conçu en silence.",
    },
  },
  EN: {
    nav: ["The Experience", "Gallery", "Reservation"],
    eyebrow: "— By reservation only",
    headlineA: "Darkness",
    headlineB: "has never been so",
    headlineC: "radiant.",
    sub: "Step into Osmose: a secret retreat in the heart of the city, crafted for intimacy and the awakening of the senses.",
    cta: "Book your interlude",
    suiteRef: "Suite N°VII · Paris",
    vertical: "Black Room — Private Edition — MMXXVI",
    scroll: "Scroll",
    manifeste: {
      kicker: "Manifesto",
      h1a: "A pause",
      h1b: "out of time,",
      h1c: "sheltered from the world.",
      body1: "Osmose is not a hotel. It is a private case, a black room conceived as an intimate theatre where every shadow and golden reflection has its reason.",
      body2: "Everything has been measured — the temperature of the light, the density of the silence, the depth of the velvet — so that nothing remains but you, and the moment.",
      signature: "Interior architect, Paris",
    },
    suite: {
      kicker: "The Suite",
      title1: "Fifty square metres",
      title2: "of carved penumbra.",
      body: "Fluted wood, washed midnight-blue cotton, low golden light. A room composed as a single breath: wide, low, enveloping.",
      specs: [
        { k: "Surface", v: "50 m²" },
        { k: "Bed", v: "King Size" },
        { k: "Capacity", v: "2 guests" },
        { k: "Acoustics", v: "Studio-grade" },
      ],
    },
    experience: {
      kicker: "The Experience",
      title1: "Three rituals",
      title2: "to forget yourself.",
      intro: "Each stay is composed like a score: three movements, one intention — slow down, feel, vanish.",
      cta: "Discover",
      tiles: [
        { num: "i.", title: "The Night Bath", body: "Private spa under sapphire light. Trembling water, steam, and the mineral glow of a suspended hour." },
        { num: "ii.", title: "The Lounge", body: "Velvet, raw marble, enveloping armchairs. A theatre of shadows for a two-voice conversation." },
        { num: "iii.", title: "The Hidden Bar", body: "Spirit cellar, hand-picked vinyls, small sweet things. Served in-room, without a word." },
      ],
    },
    galerie: {
      kicker: "Gallery",
      title1: "Traces",
      title2: "of a closed door.",
      note: "Click to enter",
      cta: "View the full gallery",
      quote: "A place where no one ever turns on all the lights — that is where everything begins.",
      quoteAuthor: "Vogue Living",
    },
    reservation: {
      kicker: "Reservation",
      title1: "Absolute discretion,",
      title2: "chiselled hospitality.",
      body: "Our concierge replies within three hours. Private code access, autonomous arrival, additional services on request.",
      f: {
        name: "Name", email: "Email", phone: "Phone",
        arrival: "Arrival", nights: "Stay", guests: "Guests",
        nightsS: "night", nightsP: "nights", guestsS: "guest", guestsP: "guests",
        message: "Particular wishes (optional)",
        submit: "Send request", submitted: "Request sent",
        disclaimer: "Confidential reply within 3h",
      },
      aside: {
        kicker: "From",
        unit: "night",
        contact: "Private concierge",
        includes: [
          "Private spa & lounge access",
          "Signature mini-bar",
          "Washed cotton linens, robes",
          "24/7 autonomous check-in",
        ],
      },
    },
    footer: {
      tagline: "A private edition at the heart of Le Marais. By reservation only.",
      col1: "House", col2: "Address", col3: "Follow",
      links1: ["The Experience", "The Suite", "Gallery", "Reservation", "Legal"],
      fine: "Crafted in silence.",
    },
  },
};
